TOOLS = {
    "project_init": {"project_name": "str", "default_branch": "str?"},
    "project_dashboard": {"include_tasks": "bool?", "limit": "int?"},
    "task_create": {
        "title": "str",
        "spec_ref": "str",
        "summary": "str?",
        "verification_mode": "manual|self-test?",
        "test_commands": "list[str]?",
        "required_doc_refs": "list[str]?",
        "required_artifacts": "list[str]?",
        "plan_node_id": "str?",
    },
    "task_list": {"status": "str?", "limit": "int?"},
    "task_transition": {"task_id": "str", "target_status": "str", "reason": "str?", "notes": "str?"},
    "task_record_verification": {"task_id": "str", "result": "passed|failed", "ref": "str?", "notes": "str?"},
    "task_record_doc_sync": {"task_id": "str", "result": "synced|outdated", "ref": "str?", "notes": "str?"},
    "task_update_acceptance_protocol": {"task_id": "str", "verification_mode": "manual|self-test?", "test_commands": "list[str]?", "required_doc_refs": "list[str]?", "required_artifacts": "list[str]?", "plan_node_id": "str?"},
    "task_run_self_test": {"task_id": "str", "workdir": "str?"},
    "spec_refresh": {"spec_ref": "str", "reason": "str?"},
    "deviation_record": {"task_id": "str", "summary": "str", "details": "str", "spec_ref": "str?"},
    "deviation_list": {},
    "task_block": {"task_id": "str", "reason": "str"},
    "task_unblock": {"task_id": "str", "target_status": "str"},
}
